### ISSUE TITLE
Verified Tags?

### ISSUE THREAD

**Issue by paddyroddy** [rickstaa/action-update-semver#11]
Thanks for the action! I was wondering if it was possible to `verify` the tags?
![image](https://github.com/rickstaa/action-update-semver/assets/15052188/004da780-2cae-4343-aa86-0ce66cfce6d5)

My workflow is something along the lines of:
```yaml
- name: Bump version and push tag
  id: bump-version
  uses: anothrNick/github-tag-action@1.67.0
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    WITH_V: true

- name: Update major tag
  uses: rickstaa/action-update-semver@v1
  with:
    major_version_tag_only: true
    tag: ${{ steps.bump-version.outputs.new_tag }}
```
