### ISSUE TITLE
[UPSTREAM_BUG] Error: fatal: not in a git directory

### ISSUE THREAD

**Issue by rickstaa** [rickstaa/action-update-semver#13]
I noticed that when I run the action with the [checkout@v4](https://github.com/actions/checkout) it triggers a `fatal: not in a git directory error when running the action.` error.

```yml
name: Update Semver
on:
  push:
    branches-ignore:
      - '**'
    tags:
      - 'v*.*.*'
jobs:
  update-semver:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: rickstaa/action-update-semver@main
```

This error was introduced in https://github.blog/2022-04-12-git-security-vulnerability-announced/; an official statement of the GitHub team about this problem can be found https://github.com/actions/checkout/issues/766.

I applied the workout suggested in https://github.com/actions/checkout/issues/766. This fix can be removed when a patch has been applied to the action ecosystem (See https://github.com/actions/checkout/issues/766). I will keep this issue open until an upstream fix has been used.
